"""Migrate cost from string to float

Revision ID: 1b6043dfe203
Revises: 8fa76892b0d8
Create Date: 2023-11-28 23:11:21.418988

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.orm import Session

from alembic import op
from wishlog.models import Item

# revision identifiers, used by Alembic.
revision: str = "1b6043dfe203"
down_revision: Union[str, None] = "8fa76892b0d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items") as batch_op:
        batch_op.alter_column(
            "cost", existing_type=sa.VARCHAR(), new_column_name="old_cost"
        )
    op.add_column("items", sa.Column("cost", sa.Float(), nullable=True, default=0))
    # ### end Alembic commands ###

    session = Session(bind=op.get_bind())

    for item in session.query(Item):
        item.cost = float(item.old_cost)

    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "items", "cost", existing_type=sa.Float(), type_=sa.VARCHAR(), nullable=True
    )
    op.drop_column("items", "old_cost")
    # ### end Alembic commands ###
