"""Add claimed date to item

Revision ID: 8fa76892b0d8
Revises: 8951ad679911
Create Date: 2023-11-27 17:59:41.240904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fa76892b0d8"
down_revision: Union[str, None] = "8951ad679911"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("claimed_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "claimed_date")
    # ### end Alembic commands ###
